#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Install coffee script
echo "* Install coffee script"
npm install -g coffee-script

# Install bots and services
echo "* Install trollo - a trello bot"
npm install -g trollo
echo "* Install paranoiapoodle - a irc notification bot"
npm install -g paranoiapoodle
echo "* Install lassie - a check and notification service"
npm install -g core-lassie

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
